### ISSUE TITLE
Typecho文章导入 插件报错

### ISSUE THREAD

**Issue by KleinerSource** [ShiinaKin/halo-plugin-typecho#1]
![image](https://github.com/ShiinaKin/halo-plugin-typecho/assets/920875/aba608d5-b172-4fd9-97ee-0ddb80035966)

启动时间: 2024-06-10 19:58
版本: 2.16.2
构建时间: 2024-06-07 11:51
Git Commit: https://github.com/halo-dev/halo/commit/7b2c8e45ffbf8759ac7459d355cc76c89bda8da5
Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
数据库: mariadb.org binary distribution / 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204
操作系统: Linux / 5.10.60-qnap
已激活主题: [Hao 1.5.2](https://github.com/chengzhongxue/halo-theme-hao)
已启动插件:
[Typecho文章导入 1.0.2](https://github.com/mashirot/halo-plugin-typecho)
[爱发电插件 1.6.1](https://github.com/carolcoral/plugin-afdian)
[Unsplash 1.1.0](https://github.com/halo-sigs/plugin-unsplash)
[KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
[Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
[Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
[AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
[图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
[瞬间 1.6.1](https://github.com/halo-sigs/plugin-moments)
[Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
[搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
[评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
[应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

**Comment by ShiinaKin** [comment]
能否提供日志文件，在halo工作目录下的logs文件夹内
