### ISSUE TITLE
我把导出一个日期的文件压缩为一个zip包导入时候报错

### ISSUE THREAD

**Issue by qgx66** [ShiinaKin/halo-plugin-typecho#2]
如图
![Uploading 1718867089831.jpg…]()

**Comment by qgx66** [comment]
![1718867089831](https://github.com/ShiinaKin/halo-plugin-typecho/assets/111854328/efb48e95-c976-4b40-9095-805940cfc6ab)

**Comment by ShiinaKin** [comment]
能否给我看下文件的结构和随便一个文章文件

**Comment by qgx66** [comment]
![1718867447239](https://github.com/ShiinaKin/halo-plugin-typecho/assets/111854328/7bd560a5-c4aa-465e-8d2f-f3166e154de7)
![1718867466449](https://github.com/ShiinaKin/halo-plugin-typecho/assets/111854328/6f348f66-1c3b-4d96-92a7-827e7cbbd3fd)
![image](https://github.com/ShiinaKin/halo-plugin-typecho/assets/111854328/18068d50-c718-4376-af50-7a90dd227f18)

**Comment by qgx66** [comment]
[2020-01-05-Docker常用命令总结.md](https://github.com/user-attachments/files/15910202/2020-01-05-Docker.md)

**Comment by ShiinaKin** [comment]
请问typecho版本是多少

**Comment by qgx66** [comment]
typecho:1.2.1

**Comment by ShiinaKin** [comment]
https://github.com/ShiinaKin/halo-plugin-typecho/actions/runs/9593499198

试试这个，直接手动上传安装

**Comment by qgx66** [comment]
> https://github.com/ShiinaKin/halo-plugin-typecho/actions/runs/9593499198
> 
> 试试这个，直接手动上传安装

![1718871956453](https://github.com/ShiinaKin/halo-plugin-typecho/assets/111854328/c997d9a4-aac4-4c73-a54c-b977936695e3)
 不兼容啥的

**Comment by ShiinaKin** [comment]
应该在v1.1.1解决了，请尝试一下
