### ISSUE TITLE
上传文件报错

### ISSUE THREAD

**Issue by movieatravelove** [ShiinaKin/halo-plugin-typecho#3]
已导出Typecho文章，并配置了插件的身份令牌，点击上传是报错如下信息：
![image](https://github.com/user-attachments/assets/1e2fdcf6-20a8-4045-ab3e-1407e84a58eb)

while scanning for the next token found character '@' that cannot start any token. (Do not use @ for indentation) in 'reader', line 5, column 7: slug: @78 ^ at [Source: (StringReader); line: 5, column: 5]

插件版本：1.1.1

**Comment by movieatravelove** [comment]
日志文件：
[halo.log](https://github.com/user-attachments/files/16406176/halo.log)

**Comment by ShiinaKin** [comment]
可以给我一个导出的blog md文件吗，你原来的文章slug前是不是有`@`

**Comment by ShiinaKin** [comment]
https://github.com/ShiinaKin/Typecho-Plugin-Tp2MD/releases/tag/v1.0.1
试试这个

**Comment by movieatravelove** [comment]
> 可以给我一个导出的blog md文件吗，你原来的文章slug前是不是有`@`

文章太多了，不知道哪个有问题哎，可以修复一下吗大佬

**Comment by movieatravelove** [comment]
> 可以给我一个导出的blog md文件吗，你原来的文章slug前是不是有`@`

文章太多了，不知道哪个有问题哎，应该是有@符号的，有代码片段。可以修复一下吗大佬

**Comment by ShiinaKin** [comment]
> > 可以给我一个导出的blog md文件吗，你原来的文章slug前是不是有`@`
> 
> 文章太多了，不知道哪个有问题哎，应该是有@符号的，有代码片段。可以修复一下吗大佬

看回复，用新发的导出插件导出试试

**Comment by movieatravelove** [comment]
> > > 可以给我一个导出的blog md文件吗，你原来的文章slug前是不是有`@`
> > 
> > 
> > 文章太多了，不知道哪个有问题哎，应该是有@符号的，有代码片段。可以修复一下吗大佬
> 
> 看回复，用新发的导出插件导出试试

不行的，一样的提示

**Comment by ShiinaKin** [comment]
随便发我一个blog下的slug带@的文件，打开来文件头就是
以及新的日志文件，麻烦了

**Comment by movieatravelove** [comment]
> 及新的日志文件，麻烦

[2019-03-29-SpringBoot_项目解决跨域问题.md](https://github.com/user-attachments/files/16421638/2019-03-29-SpringBoot_.md)
已解决，我删除了slug带@的文件之后，成功导入，感谢大佬。

**Comment by ShiinaKin** [comment]
看起来你这个md不是用我新的导出插件导出的
