### ISSUE TITLE
最后一步上传只有部分文件成功上传

### ISSUE THREAD

**Issue by noame19** [ShiinaKin/halo-plugin-typecho#5]
解析完成后后台弹出：java.lang.ClassCastException: java.lang.Integer incompatible with java.lang.String
![SS20241031-124414](https://github.com/user-attachments/assets/b3c37255-a072-4285-8141-b9998519a031)

查看halo的log：
![SS20241031-124430](https://github.com/user-attachments/assets/426e2af4-efba-4e6c-a9e0-33626856ddd5)

请问一下这个问题怎么解决？

**Comment by ShiinaKin** [comment]
能否试试手动安装这个 https://github.com/ShiinaKin/halo-plugin-typecho/actions/runs/11606718285

不行的话 方便提供一下typecho导出的文件吗

**Comment by noame19** [comment]
谢谢，试了新编译的插件，刚开始还是和之前一样小部分上传成功，然后想了一下只上传部分文件，居然全好了！然后我意识到可能是部分文件名字符出了问题，把有标题有特殊标点符号的都留了下来，慢慢一个一个试，最后居然剩下这个文件上传不了。
[2020-07-21-“一万小时理论”和“996工作制”的深思.md](https://github.com/user-attachments/files/17585100/2020-07-21-.996.md)
但是后面又改名试了一下上传，还是不行，好奇怪。。

**Comment by ShiinaKin** [comment]
感谢反馈，已在1.1.4修复
